frequency: 30
sensor_timeout: 0.1
two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

imu0: ll/imu/data_raw
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              false, false, true]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

gps0: ll/position/gps
gps0_config: [true,  true,  false,
              false, false, false,
              false, false, false,
              false, false, false]
gps0_queue_size: 5
gps0_differential: false
gps0_use_velocity: false
gps0_rejection_threshold: 5.0
gps0_nodelay: true

odom0: ll/diff_drive/measured_twist
odom0_config: [false, false, false,
               false, false, false,
               true,  true,  false,
               false, false, false]
odom0_differential: true
odom0_queue_size: 10